spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liveclass
    username: liveclass
    password: liveclass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
